import { Product, Category, BannerSlide } from '../types';
export const CATEGORIES: Category[] = [
  { id: '1', name: 'Clothing', icon: 'shirt-outline' },
  { id: '2', name: 'Shoes', icon: 'footsteps-outline' },
  { id: '3', name: 'Bags', icon: 'bag-handle-outline' },
  { id: '4', name: 'Hats', icon: 'baseball-outline' },
  { id: '5', name: 'Watches', icon: 'watch-outline' },
  { id: '6', name: 'Sunglasses', icon: 'glasses-outline' },
];
export const BANNER_SLIDES: BannerSlide[] = [
  {
    id: '1',
    title: 'Winter Deal',
    subtitle: '15% off new collection / 5% off outlet',
    tag: 'Sale',
    image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800',
    backgroundColor: '#F2F2F7',
  },
  {
    id: '2',
    title: 'New Season',
    subtitle: 'Spring collection is here',
    tag: 'New',
    image: 'https://images.unsplash.com/photo-1490114538077-0a7f8cb49891?w=800',
    backgroundColor: '#E8F0FE',
  },
  {
    id: '3',
    title: 'Flash Sale',
    subtitle: 'Up to 50% off selected items',
    tag: 'Hot',
    image: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=800',
    backgroundColor: '#FFF3E0',
  },
];
export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Red Speed T-shirt',
    price: 1299,
    originalPrice: 1799,
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600',
    images: [
      'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600',
      'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=600',
    ],
    description: 'Red cotton T-shirt with a vintage car print. Relaxed fit, ideal for casual wear.',
    category: 'Clothing',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Red', hex: '#DC2626' },
      { name: 'Purple', hex: '#9333EA' },
      { name: 'Green', hex: '#16A34A' },
    ],
    material: 'Cotton',
    length: '70cm',
    season: 'Summer',
    rating: 4.5,
    isSale: true,
    isNew: false,
  },
  {
    id: '2',
    name: 'U.S. Polo Assn',
    price: 1999,
    image: 'https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?w=600',
    description: 'Classic white polo shirt with embroidered logo. Premium cotton, comfortable fit.',
    category: 'Clothing',
    sizes: ['S', 'M', 'L'],
    colors: [
      { name: 'White', hex: '#FFFFFF' },
      { name: 'Navy', hex: '#1E3A5F' },
      { name: 'Black', hex: '#111111' },
    ],
    material: 'Cotton',
    length: '72cm',
    season: 'All Season',
    rating: 4.8,
    isNew: true,
  },
  {
    id: '3',
    name: 'Carhartt Striped Shirt',
    price: 1499,
    originalPrice: 2199,
    image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600',
    description: 'Classic striped button-down shirt. Relaxed fit with premium cotton blend.',
    category: 'Clothing',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'White', hex: '#FFFFFF' },
      { name: 'Blue', hex: '#3B82F6' },
    ],
    material: 'Cotton Blend',
    length: '74cm',
    season: 'Spring',
    rating: 4.3,
    isSale: true,
  },
  {
    id: '4',
    name: 'Maison Zip-up Cardigan',
    price: 3499,
    image: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600',
    description: 'Premium zip-up cardigan in warm brown. Perfect layering piece for cooler days.',
    category: 'Clothing',
    sizes: ['M', 'L', 'XL'],
    colors: [
      { name: 'Brown', hex: '#92400E' },
      { name: 'Black', hex: '#111111' },
      { name: 'Gray', hex: '#6B7280' },
    ],
    material: 'Wool Blend',
    length: '68cm',
    season: 'Winter',
    rating: 4.7,
    isNew: true,
  },
  {
    id: '5',
    name: 'Blue Striped Shirt',
    price: 1599,
    image: 'https://images.unsplash.com/photo-1598033129183-c4f50c736c10?w=600',
    description: 'Light blue striped casual shirt. Breathable fabric, perfect for summer.',
    category: 'Clothing',
    sizes: ['S', 'M', 'L'],
    colors: [
      { name: 'Blue', hex: '#3B82F6' },
      { name: 'White', hex: '#FFFFFF' },
    ],
    material: 'Linen',
    length: '73cm',
    season: 'Summer',
    rating: 4.2,
  },
  {
    id: '6',
    name: 'Classic Black Sneakers',
    price: 2999,
    originalPrice: 3999,
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600',
    description: 'Minimalist black sneakers with premium leather upper and comfortable sole.',
    category: 'Shoes',
    sizes: ['40', '41', '42', '43', '44'],
    colors: [
      { name: 'Black', hex: '#111111' },
      { name: 'White', hex: '#FFFFFF' },
    ],
    material: 'Leather',
    season: 'All Season',
    rating: 4.6,
    isSale: true,
  },
  {
    id: '7',
    name: 'Leather Crossbody Bag',
    price: 4499,
    image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600',
    description: 'Genuine leather crossbody bag with adjustable strap. Spacious interior.',
    category: 'Bags',
    sizes: ['One Size'],
    colors: [
      { name: 'Brown', hex: '#92400E' },
      { name: 'Black', hex: '#111111' },
    ],
    material: 'Genuine Leather',
    season: 'All Season',
    rating: 4.9,
    isNew: true,
  },
  {
    id: '8',
    name: 'Wool Fedora Hat',
    price: 899,
    image: 'https://images.unsplash.com/photo-1514327605112-b887c0e61c0a?w=600',
    description: 'Classic wool fedora hat. Timeless style with modern comfort.',
    category: 'Hats',
    sizes: ['S', 'M', 'L'],
    colors: [
      { name: 'Gray', hex: '#6B7280' },
      { name: 'Black', hex: '#111111' },
      { name: 'Brown', hex: '#92400E' },
    ],
    material: 'Wool',
    season: 'Autumn',
    rating: 4.4,
  },
  {
    id: '9',
    name: 'Slim Fit Chinos',
    price: 1899,
    originalPrice: 2499,
    image: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=600',
    description: 'Slim fit chinos with stretch fabric. Perfect for smart casual looks.',
    category: 'Clothing',
    sizes: ['28', '30', '32', '34', '36'],
    colors: [
      { name: 'Khaki', hex: '#C2B280' },
      { name: 'Navy', hex: '#1E3A5F' },
      { name: 'Black', hex: '#111111' },
    ],
    material: 'Cotton Stretch',
    season: 'All Season',
    rating: 4.5,
    isSale: true,
  },
  {
    id: '10',
    name: 'Denim Jacket',
    price: 3299,
    image: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=600',
    description: 'Classic denim jacket with modern wash. Versatile layering essential.',
    category: 'Clothing',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Blue', hex: '#3B82F6' },
      { name: 'Black', hex: '#111111' },
    ],
    material: 'Denim',
    season: 'All Season',
    rating: 4.7,
    isNew: true,
  },
];
export default PRODUCTS;
